name: Playwright C# Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest  # Use Windows runner since Playwright C# works better on Windows

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Use the .NET version your project targets (e.g., 8.0, 7.0, or 6.0)

    - name: Restore dependencies
      run: dotnet restore PlaywrightTests.sln

    - name: Install Playwright browsers
      run: |
        dotnet tool install --global Microsoft.Playwright.CLI
        playwright install

    - name: Build the solution
      run: dotnet build PlaywrightTests.sln --configuration Release --no-restore

    - name: Run Playwright tests
      run: dotnet test PlaywrightTests.sln --no-build --verbosity normal
      working-directory: .  # Adjust if tests are in a subdirectory, e.g., PlaywrightTests

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: PlaywrightTests/TestResults/  # Adjust based on your test output directory
